srsv2:
    image:zhouweitong/srs-docker:v2
    ports:
        - 443:443
        - 554:554
        - 1935:1935
        - 1985:1985
        - 2037:2037
        - 2038:2038
        - 2039:2039
        - 2040:2040
        - 8080:8080
        - 8081:8081
        - 8082:8082
        - 8443:8443
        - 8936:8936
        - 50000-51000:50000-51000
        - 57000-58000:57200-57300
    volumes:
        - /tmp/srsv2/logs:/root/logs
        - /tmp/srsv2/shell:/root/shell
        - /tmp/srsv2/sample_conf :/root/sample_conf